#!/usr/bin/env node
/**
 * Regenerate reference material from openly-licensed authoritative sources.
 *
 * Sources and licensing — ONLY openly-licensed specs are ingested:
 *   - W3C WCAG 2.2 (w3.org)  — W3C Document License / W3C Software and Document License
 *
 * DELIBERATELY NOT INGESTED:
 *   - Apple Human Interface Guidelines. Apple's content is copyrighted and its terms are
 *     restrictive. Do not add it, even generated locally.
 *   - MDN prose. MDN is CC-BY-SA, which is share-alike; quoting short factual values in
 *     hand-written skills is fine, but bulk-ingesting prose into an MIT plugin is not.
 *
 * Usage:
 *   node scripts/pull-refs.mjs                 regenerate references/
 *   node scripts/pull-refs.mjs --check         verify freshness, write nothing (exit 1 if stale)
 *   node scripts/pull-refs.mjs --force-prune   allow deleting more than the prune limit
 *
 * Idempotence is the test: running twice must produce zero git diff.
 *   node scripts/pull-refs.mjs && git status --short
 */

import { writeFile, readFile, readdir, mkdir, unlink } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = join(ROOT, 'references');

const WCAG22_JSON = 'https://www.w3.org/WAI/WCAG22/wcag.json';
const WCAG22_URL = 'https://www.w3.org/TR/WCAG22/';

// A generated file is identified by this marker; anything without it is curated and never pruned.
const GENERATED_MARKER = '<!-- generated by scripts/pull-refs.mjs -->';

// Fail-closed prune guards: a run that wants to delete a large share of files almost certainly
// means a broken fetch, not upstream removals.
const PRUNE_SHARE_LIMIT = 0.1;
const PRUNE_COUNT_FLOOR = 3;

const args = new Set(process.argv.slice(2));
const CHECK_ONLY = args.has('--check');
const FORCE_PRUNE = args.has('--force-prune');

async function fetchJson(url) {
  const res = await fetch(url, { headers: { accept: 'application/json' } });
  if (!res.ok) throw new Error(`GET ${url} -> HTTP ${res.status}`);
  return res.json();
}

/** Flatten the WCAG JSON tree into one row per success criterion. */
function extractCriteria(doc) {
  const rows = [];

  for (const principle of doc.principles ?? []) {
    for (const guideline of principle.guidelines ?? []) {
      for (const sc of guideline.successcriteria ?? []) {
        rows.push({
          num: sc.num,
          id: sc.id,
          level: sc.level,
          handle: sc.handle,
          title: (sc.title ?? '').replace(/\s+/g, ' ').trim(),
          principle: principle.handle,
          guideline: `${guideline.num} ${guideline.handle}`,
        });
      }
    }
  }

  // Numeric sort so 2.4.11 follows 2.4.9 rather than sorting as a string.
  rows.sort((a, b) => {
    const pa = a.num.split('.').map(Number);
    const pb = b.num.split('.').map(Number);
    return pa[0] - pb[0] || pa[1] - pb[1] || pa[2] - pb[2];
  });

  return rows;
}

function renderCriteriaTable(rows) {
  const lines = [
    GENERATED_MARKER,
    `> Source: <${WCAG22_URL}>`,
    '> Generated by `scripts/pull-refs.mjs` — do not edit by hand.',
    '> W3C content, used under the W3C Document License.',
    '',
    '# WCAG 2.2 success criteria',
    '',
    `${rows.length} success criteria.`,
    '',
  ];

  for (const level of ['A', 'AA', 'AAA']) {
    const group = rows.filter((r) => r.level === level);
    lines.push(`## Level ${level} (${group.length})`, '', '| SC | Name | Principle |', '|---|---|---|');
    for (const r of group) {
      lines.push(`| [${r.num}](${WCAG22_URL}#${r.id}) | ${r.handle} | ${r.principle} |`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

/** Files this script generated, identified by the marker in their first bytes. */
async function generatedFiles(dir) {
  let names;
  try {
    names = await readdir(dir);
  } catch {
    return [];
  }

  const out = [];
  for (const name of names) {
    if (!name.endsWith('.md')) continue;
    const head = (await readFile(join(dir, name), 'utf8')).slice(0, 400);
    if (head.includes(GENERATED_MARKER)) out.push(name);
  }
  return out;
}

async function main() {
  console.log(`Fetching WCAG 2.2 from ${WCAG22_JSON}`);
  const doc = await fetchJson(WCAG22_JSON);
  const rows = extractCriteria(doc);

  // Fail closed: write nothing if the shape changed and we parsed nothing useful.
  if (rows.length === 0) {
    throw new Error(
      'Parsed 0 success criteria. The upstream format may have changed. Nothing was written.'
    );
  }
  if (rows.length < 50) {
    throw new Error(
      `Parsed only ${rows.length} success criteria; expected 80+. Refusing to write a truncated reference.`
    );
  }

  const files = new Map([['wcag22-criteria.md', renderCriteriaTable(rows)]]);

  const aa = rows.filter((r) => r.level === 'AA').length;
  console.log(`Parsed ${rows.length} criteria (${aa} at Level AA)`);

  if (CHECK_ONLY) {
    let stale = 0;
    for (const [name, content] of files) {
      const current = await readFile(join(OUT_DIR, name), 'utf8').catch(() => null);
      if (current !== content) {
        console.error(`STALE: references/${name}`);
        stale++;
      }
    }
    if (stale) {
      console.error(`\n${stale} file(s) out of date. Run: node scripts/pull-refs.mjs`);
      process.exit(1);
    }
    console.log('All references up to date.');
    return;
  }

  await mkdir(OUT_DIR, { recursive: true });

  for (const [name, content] of files) {
    await writeFile(join(OUT_DIR, name), content, 'utf8');
    console.log(`Wrote references/${name}`);
  }

  // Prune stale generated files, guarded against mass deletion from a broken run.
  const existing = await generatedFiles(OUT_DIR);
  const orphans = existing.filter((n) => !files.has(n));

  if (orphans.length) {
    const limit = Math.max(PRUNE_COUNT_FLOOR, Math.floor(existing.length * PRUNE_SHARE_LIMIT));
    if (orphans.length > limit && !FORCE_PRUNE) {
      console.error(
        `Refusing to prune ${orphans.length} of ${existing.length} generated files (limit ${limit}).\n` +
          'A large prune usually means a broken crawl. Re-run with --force-prune if this is intended.'
      );
      process.exit(1);
    }
    for (const name of orphans) {
      await unlink(join(OUT_DIR, name));
      console.log(`Pruned references/${name}`);
    }
  }

  console.log('\nDone. Verify idempotence with: git status --short');
}

main().catch((err) => {
  console.error(`\nFAILED: ${err.message}`);
  process.exit(1);
});
